import oracledb
import sys

db_config = {
    "user": "system",
    "password": "1234",
    "dsn": "localhost:1521/xe"
}

def get_connection():
    try:
        conn = oracledb.connect(
            user=db_config["user"],
            password=db_config["password"],
            dsn=db_config["dsn"]
        )
        return conn
    except oracledb.Error as e:
        print(f"  DB 접속 실패: {e}")
        sys.exit(1)

def setup_database(cursor):
    try:
        cursor.execute("DROP TABLE GRADES_MASTER")
    except oracledb.Error:
        pass

    cursor.execute("""
        CREATE TABLE GRADES_MASTER (
            STD_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            STU_NAME VARCHAR2(50) NOT NULL,
            KOR NUMBER NOT NULL,
            ENG NUMBER NOT NULL,
            MATH NUMBER NOT NULL,
            HISTORY NUMBER NOT NULL,
            SCIENCE NUMBER NOT NULL,
            TEACHER_NOTE VARCHAR2(200)
        )
    """)

def insert_database(cursor, grade_string, students):
    grades = grade_string.split(',')

    insert_sql = "INSERT INTO GRADES_MASTER (STU_NAME, KOR, ENG, MATH, HISTORY, SCIENCE) VALUES (:1, :2, :3, :4, :5, :6)"
    inserted_count = 0

    for item in grades:
        item = item.strip()
        if item in students:
            cursor.execute(insert_sql, (item, students[item]))
            inserted_count += 1
        else:
            print(f"'{item}'은 존재하지 않는 학생입니다.")
    return inserted_count

def grade_report(cursor):
    query = """
        SELECT COUNT(*) AS GRADE,
            (KOR + ENG + MATH + HISTORY + SCIENCE) / 5 AS AVG,
            MAX GRADE,
            MIN GRADE
        FROM GRADES_MASTER
    """
    cursor.execute(query)
    return cursor.fetchone()

def student_search(cursor):
    query = """
        SELECT STU_NAME,
            COUNT(*) AS GRADE,
            RANK
        FROM GRADES_MASTER
    """
    cursor.execute(query)
    return cursor.fetchone()

if __name__ == '__main__':
    
    students = {
        "홍길동" : [],
        "성춘향" : []
        }

    conn = get_connection()
    cursor = conn.cursor()

    try:
        setup_database(cursor)

        while True:
            print("\n" + "=" *30)
            print(" 성적 관리 시스템")
            print("1. 교사 모드")
            print("2. 학생 모드")
            print("3. 종료")
            print("="*30)
            
            choice = input("선택> ")

            if choice == '1':
                data_input = input("\n > 성적을 입력하세요 (이름, 국, 영, 수, 사, 과)\n> ")
                student_name = insert_database(cursor, data_input)
                if student_name:
                    cursor.execute("UPDATE GRADES_MASTER SET TEACHER_NOTE = :1 WHERE STU_NAME = :2", 
                                 ["전 과목 우수합니다. 지금처럼 열공하세요!", student_name])
                    conn.commit()
                    print(f"\n DB 저장 성공! [{student_name}] 학생의 데이터가 저장 되었습니다.")
                    grade_report(cursor)

            elif choice == '2':
                search_name = input("\n본인 이름을 입력하세요: ")

            elif choice == '3':
                print("프로그램을 종료합니다.")
                break
    
    except oracledb.Error as e:
        print(f" 오류 발생: {e}")
        conn.rollback()
    finally:
        cursor.close()
        conn.close()
    